"""Capture one live pull and freeze it as a committed fixture.

Run this deliberately, never as part of a test. Re-running it changes every
published figure, which is why the regression suite compares against what it wrote
rather than against a fresh pull.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

from clab.data.loader import load_company, load_deflator, load_fx, load_rates
from clab.universe import UNIVERSE

FIXTURES = Path(__file__).resolve().parents[1] / "tests" / "fixtures"
STATEMENTS = FIXTURES / "statements"


def _slug(ticker: str) -> str:
    return ticker.replace(".", "_").replace("-", "_")


def main() -> None:
    STATEMENTS.mkdir(parents=True, exist_ok=True)
    written = 0
    for company in UNIVERSE:
        data = load_company(company)
        slug = _slug(company.ticker)
        for label, frame in (
            ("balance", data.balance_sheet),
            ("income", data.income),
            ("cashflow", data.cashflow),
        ):
            frame.to_csv(STATEMENTS / f"{slug}_{label}.csv")
            written += 1
        data.prices.to_frame("Close").to_csv(STATEMENTS / f"{slug}_prices.csv")
        written += 1

    load_rates().to_csv(FIXTURES / "rates.csv")
    load_deflator().to_frame("GDPDEF").to_csv(FIXTURES / "deflator.csv")
    load_fx().to_csv(FIXTURES / "fx.csv")
    written += 3

    (FIXTURES / "frozen.py").write_text(
        '"""Replay of the frozen capture, so the suite runs with no network.\n\n'
        "Regenerated by scripts/build_fixture.py. Re-running that script changes every\n"
        'published figure, which is why it is never called from a test."""\n\n'
        "from __future__ import annotations\n\n"
        "from pathlib import Path\n\n"
        "import pandas as pd\n\n"
        "from clab.data.loader import CompanyData\n"
        "from clab.universe import UNIVERSE, by_ticker\n\n"
        f'CAPTURED = "{date.today().isoformat()}"\n'
        "FIXTURES = Path(__file__).parent\n"
        'STATEMENTS = FIXTURES / "statements"\n\n\n'
        "def _slug(ticker: str) -> str:\n"
        '    return ticker.replace(".", "_").replace("-", "_")\n\n\n'
        "def _frame(name: str) -> pd.DataFrame:\n"
        "    return pd.read_csv(STATEMENTS / name, index_col=0, parse_dates=True)\n\n\n"
        "def load() -> dict:\n"
        "    loaded = {}\n"
        "    for company in UNIVERSE:\n"
        "        slug = _slug(company.ticker)\n"
        "        loaded[company.ticker] = CompanyData(\n"
        "            by_ticker(company.ticker),\n"
        '            _frame(f"{slug}_balance.csv"),\n'
        '            _frame(f"{slug}_income.csv"),\n'
        '            _frame(f"{slug}_cashflow.csv"),\n'
        '            _frame(f"{slug}_prices.csv")["Close"],\n'
        "        )\n"
        "    return {\n"
        '        "loaded": loaded,\n'
        '        "rates": pd.read_csv(FIXTURES / "rates.csv", index_col=0, parse_dates=True),\n'
        '        "deflator": pd.read_csv(\n'
        '            FIXTURES / "deflator.csv", index_col=0, parse_dates=True\n'
        '        )["GDPDEF"],\n'
        '        "fx": pd.read_csv(FIXTURES / "fx.csv", index_col=0, parse_dates=True),\n'
        "    }\n",
        encoding="utf-8",
    )
    print(f"froze {written} files under {FIXTURES}")


if __name__ == "__main__":
    main()
