"""Replay of the frozen capture, so the suite runs with no network.

Regenerated by scripts/build_fixture.py. Re-running that script changes every
published figure, which is why it is never called from a test."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from clab.data.loader import CompanyData
from clab.universe import UNIVERSE, by_ticker

CAPTURED = "2026-08-07"
FIXTURES = Path(__file__).parent
STATEMENTS = FIXTURES / "statements"


def _slug(ticker: str) -> str:
    return ticker.replace(".", "_").replace("-", "_")


def _frame(name: str) -> pd.DataFrame:
    return pd.read_csv(STATEMENTS / name, index_col=0, parse_dates=True)


def load() -> dict:
    loaded = {}
    for company in UNIVERSE:
        slug = _slug(company.ticker)
        loaded[company.ticker] = CompanyData(
            by_ticker(company.ticker),
            _frame(f"{slug}_balance.csv"),
            _frame(f"{slug}_income.csv"),
            _frame(f"{slug}_cashflow.csv"),
            _frame(f"{slug}_prices.csv")["Close"],
        )
    return {
        "loaded": loaded,
        "rates": pd.read_csv(FIXTURES / "rates.csv", index_col=0, parse_dates=True),
        "deflator": pd.read_csv(
            FIXTURES / "deflator.csv", index_col=0, parse_dates=True
        )["GDPDEF"],
        "fx": pd.read_csv(FIXTURES / "fx.csv", index_col=0, parse_dates=True),
    }
